services:
  - type: web
    name: quest-frontend
    runtime: image
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: NEXT_PUBLIC_API_BASE_URL
        value: https://quest-backend-a9nv.onrender.com
